server:
  port: 8006

# 阿里云 API配置信息
oss:
  # 内或外网域名
  endpoint: oss-cn-beijing.aliyuncs.com
  # 密钥Access Key ID
  access-key-id: LTAI5tPehJx4fr1DwBjt8p3E
  # 密钥Access Key Secret
  access-key-secret: dwQKWZWGHC7f2J2Dk67yeZA1qVJLhE