server:
  port: 8007

spring:
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names: master, slave0, slave1
      # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
        username: root
        password: 123456
      # 从数据源
      slave0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
        username: root
        password: 123456
      slave1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
        username: root
        password: 123456
    # 读写分离配置
    masterslave:
      # 读写分离数据源名称
      name: dataSource
      # 主库数据源名称
      master-data-source-name: master
      # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names:
        - slave0
        - slave1
      # 从库负载均衡算法类型，可选值：ROUND_ROBIN，RANDOM。若`loadBalanceAlgorithmClassName`存在则忽略该配置
      load-balance-algorithm-type: round_robin
    props:
      # 开启SQL显示，默认false
      sql:
        show: true

mybatis-plus:
  mapper-locations: classpath:quick/sharding/jdbc/mapper/xml/*.xml,classpath*:/mapper/*.xml
  type-aliases-package: quick.sharding.jdbc.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true # 表名是否使用下划线命名，默认数据库表使用下划线命名
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql