server:
  port: 8008

#数据源
spring:
  datasource:
    #默认数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: 123456
    initialSize: 1
    minIdle: 5
    maxActive: 20
#其他数据源
slave:
  datasource:
    names: ds1,ds2
  #ds1
    ds1:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test1
      username: root
      password: 123456
      initialSize: 1
      minIdle: 5
      maxActive: 20
  #ds2
    ds2:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test1
      username: root
      password: 123456
      initialSize: 1
      minIdle: 5
      maxActive: 20
        
#mapper.xml文件
mybatis:
  mapper-locations: classpath:quick/dynamic/datasource/mapper/xml/*.xml,classpath*:/mapper/*.xml
  type-aliases-packag: quick.dynamic.datasource.entity